/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as NamingRouteImport } from './routes/naming'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as DemoConsultRouteImport } from './routes/demo/consult'
import { Route as DemoRentRouteImport } from './routes/demo/rent'
import { Route as DemoTuitionRouteImport } from './routes/demo/tuition'
import { Route as PaperIdRouteImport } from './routes/paper/$id'
import { Route as ReceiptsIdRouteImport } from './routes/receipts/$id'
import { Route as RefusalIdRouteImport } from './routes/refusal/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const NamingRoute = NamingRouteImport.update({
  id: '/naming',
  path: '/naming',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConsultRoute = DemoConsultRouteImport.update({
  id: '/demo/consult',
  path: '/demo/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRentRoute = DemoRentRouteImport.update({
  id: '/demo/rent',
  path: '/demo/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTuitionRoute = DemoTuitionRouteImport.update({
  id: '/demo/tuition',
  path: '/demo/tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperIdRoute = PaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusalIdRoute = RefusalIdRouteImport.update({
  id: '/refusal/$id',
  path: '/refusal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/challenge': typeof ChallengeRoute
  '/circles': typeof CirclesRoute
  '/doctrine': typeof DoctrineRoute
  '/naming': typeof NamingRoute
  '/policies': typeof PoliciesRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/workshop': typeof WorkshopRoute
  '/demo/consult': typeof DemoConsultRoute
  '/demo/rent': typeof DemoRentRoute
  '/demo/tuition': typeof DemoTuitionRoute
  '/paper/$id': typeof PaperIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/refusal/$id': typeof RefusalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/challenge': typeof ChallengeRoute
  '/circles': typeof CirclesRoute
  '/doctrine': typeof DoctrineRoute
  '/naming': typeof NamingRoute
  '/policies': typeof PoliciesRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/workshop': typeof WorkshopRoute
  '/demo/consult': typeof DemoConsultRoute
  '/demo/rent': typeof DemoRentRoute
  '/demo/tuition': typeof DemoTuitionRoute
  '/paper/$id': typeof PaperIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/refusal/$id': typeof RefusalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/challenge': typeof ChallengeRoute
  '/circles': typeof CirclesRoute
  '/doctrine': typeof DoctrineRoute
  '/naming': typeof NamingRoute
  '/policies': typeof PoliciesRoute
  '/registry': typeof RegistryRoute
  '/verify': typeof VerifyRoute
  '/workshop': typeof WorkshopRoute
  '/demo/consult': typeof DemoConsultRoute
  '/demo/rent': typeof DemoRentRoute
  '/demo/tuition': typeof DemoTuitionRoute
  '/paper/$id': typeof PaperIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/refusal/$id': typeof RefusalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/challenge'
    | '/circles'
    | '/doctrine'
    | '/naming'
    | '/policies'
    | '/registry'
    | '/verify'
    | '/workshop'
    | '/demo/consult'
    | '/demo/rent'
    | '/demo/tuition'
    | '/paper/$id'
    | '/receipts/$id'
    | '/refusal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/challenge'
    | '/circles'
    | '/doctrine'
    | '/naming'
    | '/policies'
    | '/registry'
    | '/verify'
    | '/workshop'
    | '/demo/consult'
    | '/demo/rent'
    | '/demo/tuition'
    | '/paper/$id'
    | '/receipts/$id'
    | '/refusal/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/challenge'
    | '/circles'
    | '/doctrine'
    | '/naming'
    | '/policies'
    | '/registry'
    | '/verify'
    | '/workshop'
    | '/demo/consult'
    | '/demo/rent'
    | '/demo/tuition'
    | '/paper/$id'
    | '/receipts/$id'
    | '/refusal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChallengeRoute: typeof ChallengeRoute
  CirclesRoute: typeof CirclesRoute
  DoctrineRoute: typeof DoctrineRoute
  NamingRoute: typeof NamingRoute
  PoliciesRoute: typeof PoliciesRoute
  RegistryRoute: typeof RegistryRoute
  VerifyRoute: typeof VerifyRoute
  WorkshopRoute: typeof WorkshopRoute
  DemoConsultRoute: typeof DemoConsultRoute
  DemoRentRoute: typeof DemoRentRoute
  DemoTuitionRoute: typeof DemoTuitionRoute
  PaperIdRoute: typeof PaperIdRoute
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  RefusalIdRoute: typeof RefusalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naming': {
      id: '/naming'
      path: '/naming'
      fullPath: '/naming'
      preLoaderRoute: typeof NamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/consult': {
      id: '/demo/consult'
      path: '/demo/consult'
      fullPath: '/demo/consult'
      preLoaderRoute: typeof DemoConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rent': {
      id: '/demo/rent'
      path: '/demo/rent'
      fullPath: '/demo/rent'
      preLoaderRoute: typeof DemoRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tuition': {
      id: '/demo/tuition'
      path: '/demo/tuition'
      fullPath: '/demo/tuition'
      preLoaderRoute: typeof DemoTuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper/$id': {
      id: '/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof PaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refusal/$id': {
      id: '/refusal/$id'
      path: '/refusal/$id'
      fullPath: '/refusal/$id'
      preLoaderRoute: typeof RefusalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChallengeRoute: ChallengeRoute,
  CirclesRoute: CirclesRoute,
  DoctrineRoute: DoctrineRoute,
  NamingRoute: NamingRoute,
  PoliciesRoute: PoliciesRoute,
  RegistryRoute: RegistryRoute,
  VerifyRoute: VerifyRoute,
  WorkshopRoute: WorkshopRoute,
  DemoConsultRoute: DemoConsultRoute,
  DemoRentRoute: DemoRentRoute,
  DemoTuitionRoute: DemoTuitionRoute,
  PaperIdRoute: PaperIdRoute,
  ReceiptsIdRoute: ReceiptsIdRoute,
  RefusalIdRoute: RefusalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
